src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

src/fundiy/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views
# to make home point to product_list
from orders.views import order_create
from shop.views import product_list

urlpatterns = [
    # 让主页指向产品列表
    url(r'^$', product_list, name='home'),
    # make sure include cart.urls before shop.urls
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # make sure inlcude orders.urls before shop.urls
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include(accounts.urls, namespace='accounts')),

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import JSONField


class BaseProfile(models.Model):
    TYPE_OF_USERS = (
        (None, '选择用户类型'),
        ('customer', '客户'),
        ('designer', '设计师'),
        ('maker', '制造商'),
        ('seller', '销售员'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True, verbose_name="用户")
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    picture = models.ImageField('用户照片',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("个人简介", max_length=200, blank=True, null=True)
    first_name = models.CharField("名字", max_length=200, null=True)
    last_name = models.CharField("姓氏", max_length=200, null=True)

    user_type = models.CharField("用户类型", choices=TYPE_OF_USERS, max_length=20, null=True)
    phone = models.CharField("手机号", max_length=20, null=True)
    # User's address information
    country = models.CharField('国家', max_length=50, null=True)
    province = models.CharField('省份', max_length=50, null=True)
    city = models.CharField('城市', max_length=50, null=True)
    county = models.CharField('区县', max_length=50, null=True)
    street = models.CharField('详细地址', max_length=200, null=True)
    # Shipping address for the user
    ship_address = JSONField('送货地址', null=True)
    # The bank account or other financial accounts used for user's profit.
    income = models.PositiveIntegerField('销售收入', null=True)
    accounts = JSONField('资金帐户', null=True)


    email_verified = models.BooleanField("邮件地址", default=False)

    class Meta:
        abstract = True
        verbose_name = "详细信息"
        verbose_name_plural = "详细信息"


@python_2_unicode_compatible
class Profile(BaseProfile):

    def __str__(self):
        return "{}'s profile". format(self.user)

src/profiles/forms.py
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model
from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
            )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('last_name'),
            Field('first_name'),
            Field('picture'),
            Field('bio'),
            Field('phone'),
            Field('country'),
            Field('province'),
            Field('city'),
            Field('county'),
            Field('street'),
            Submit('update', '更新', css_class="btn-success"),
            )

    class Meta:
        model = models.Profile
        fields = ['last_name', 'first_name', 'picture', 'bio','phone', 'country', 'province', 'city', 'county', 'street']

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}个人信息{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">编辑个人信息</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="用户照片" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>个人详细信息</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">更改密码</a>
    </div>
  </div>
</div>
{% endblock %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}详细信息{% endblock %}

{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">编辑个人信息</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="个人照片" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">个人信息</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>邮件地址:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="此邮件地址已经经过验证"></span>
	    <span class="sr-only">已验证</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="此邮件地址没有经过验证"></span>
	    <span class="sr-only">没有验证</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>加入时间</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>上一次登录</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}的个人信息
	  {% if show_user.profile.slug %}
	    <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    	<span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    	<span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
	  {% else %}
		<a href="https://github.com/arocks/edge/issues/40" target="_blank"><span>No permalink. See this issue.</span></a>
	  {% endif %}
	</div>
        <div class="panel-body">
	  <strong>个人简介</strong>: {{ show_user.profile.bio }}

	</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}